"""M1 designation-duty + export identity

Revision ID: 395978142ea1
Revises: fd6950ad2397
Create Date: 2026-06-20 00:09:16.975152
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import server.db.types

# revision identifiers, used by Alembic.
revision: str = '395978142ea1'
down_revision: Union[str, None] = 'fd6950ad2397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('designations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('per_unit_designated_duty', server.db.types.Money(), nullable=False))

    with op.batch_alter_table('export_lines', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_export_lines_client_id'), ['client_id', 'reference'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('export_lines', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_export_lines_client_id'), type_='unique')

    with op.batch_alter_table('designations', schema=None) as batch_op:
        batch_op.drop_column('per_unit_designated_duty')

    # ### end Alembic commands ###
