"""M2 tenant_id on program/claim/checklist (RLS)

Revision ID: e5e0f657ab44
Revises: 395978142ea1
Create Date: 2026-06-20 00:37:34.312926
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5e0f657ab44'
down_revision: Union[str, None] = '395978142ea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=32), nullable=False))
        batch_op.create_index(batch_op.f('ix_checklist_items_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_checklist_items_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=32), nullable=False))
        batch_op.create_index(batch_op.f('ix_claims_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_claims_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=32), nullable=False))
        batch_op.create_index(batch_op.f('ix_programs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_programs_tenant_id_tenants'), 'tenants', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_programs_tenant_id_tenants'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_programs_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_claims_tenant_id_tenants'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_claims_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_checklist_items_tenant_id_tenants'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_checklist_items_tenant_id'))
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
