"""initial domain schema (M0)

Revision ID: fd6950ad2397
Revises: 
Create Date: 2026-06-19 23:49:38.759066
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import server.db.types

# revision identifiers, used by Alembic.
revision: str = 'fd6950ad2397'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('broker_firm', 'self_filer', name='tenant_kind', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants'))
    )
    op.create_table('clients',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('importer_id', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_clients_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients'))
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('programs',
    sa.Column('client_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('drawback_type', sa.Enum('j1', 'j2', 'a', 'b', 'c', name='drawback_type', native_enum=False, length=32), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('mfg_ruling_ref', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_programs_client_id_clients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programs'))
    )
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_programs_client_id'), ['client_id'], unique=False)

    op.create_table('users',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'preparer', 'reviewer', 'signer', 'client', name='user_role', native_enum=False, length=32), nullable=False),
    sa.Column('client_scope_id', sa.String(length=32), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_scope_id'], ['clients.id'], name=op.f('fk_users_client_scope_id_clients')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('tenant_id', 'email', name=op.f('uq_users_tenant_id'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('audit_events',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('actor_user_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_events_actor_user_id_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audit_events_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('claims',
    sa.Column('program_id', sa.String(length=32), nullable=False),
    sa.Column('period', sa.String(length=64), nullable=True),
    sa.Column('mode', sa.Enum('retroactive', 'periodic', name='claim_mode', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('draft', 'ready', 'filed', 'under_review', 'liquidated', 'paid', name='claim_status', native_enum=False, length=32), nullable=False),
    sa.Column('filed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('liquidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_refund', server.db.types.Money(), nullable=True),
    sa.Column('defensible_refund', server.db.types.Money(), nullable=True),
    sa.Column('actual_refund', server.db.types.Money(), nullable=True),
    sa.Column('claim_number', sa.String(length=64), nullable=True),
    sa.Column('signoff', sa.JSON(), nullable=True),
    sa.Column('tariff_config_version', sa.String(length=32), nullable=True),
    sa.Column('as_of', sa.Date(), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_claims_program_id_programs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims'))
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_status'), ['status'], unique=False)

    op.create_table('documents',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('doc_type', sa.Enum('form_7501', 'bill_of_lading', 'aes_eei', 'invoice', 'form_7553', 'bom', 'other', name='doc_type', native_enum=False, length=32), nullable=False),
    sa.Column('blob_ref', sa.String(length=1024), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('extracted', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'ocr_done', 'matched', 'needs_review', 'confirmed', name='doc_status', native_enum=False, length=32), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=True),
    sa.Column('claim_id', sa.String(length=32), nullable=True),
    sa.Column('retention_until', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_documents_claim_id_claims')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_documents_client_id_clients')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_documents_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tasks',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('claim_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.Enum('gap', 'chase', 'client_request', 'review', name='task_kind', native_enum=False, length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner_user_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'done', 'cancelled', name='task_status', native_enum=False, length=32), nullable=False),
    sa.Column('related_line_id', sa.String(length=32), nullable=True),
    sa.Column('client_request_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_tasks_claim_id_claims')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_tasks_owner_user_id_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tasks_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('checklist_items',
    sa.Column('claim_id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('satisfied_by_document_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('pending', 'satisfied', 'not_applicable', name='checklist_status', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_checklist_items_claim_id_claims')),
    sa.ForeignKeyConstraint(['satisfied_by_document_id'], ['documents.id'], name=op.f('fk_checklist_items_satisfied_by_document_id_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checklist_items'))
    )
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_items_claim_id'), ['claim_id'], unique=False)

    op.create_table('export_lines',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('hts10', sa.String(length=10), nullable=False),
    sa.Column('export_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('uom', sa.String(length=16), nullable=False),
    sa.Column('value_per_unit', server.db.types.Money(), nullable=False),
    sa.Column('has_export_proof', sa.Boolean(), nullable=False),
    sa.Column('itn', sa.String(length=64), nullable=True),
    sa.Column('proof_document_id', sa.String(length=32), nullable=True),
    sa.Column('direct_id_entry', sa.String(length=32), nullable=True),
    sa.Column('direct_id_line', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_export_lines_client_id_clients')),
    sa.ForeignKeyConstraint(['proof_document_id'], ['documents.id'], name=op.f('fk_export_lines_proof_document_id_documents')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_export_lines_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_export_lines'))
    )
    with op.batch_alter_table('export_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_lines_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_lines_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('import_entry_lines',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.String(length=32), nullable=False),
    sa.Column('entry_number', sa.String(length=32), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('hts10', sa.String(length=10), nullable=False),
    sa.Column('import_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('uom', sa.String(length=16), nullable=False),
    sa.Column('entered_value', server.db.types.Money(), nullable=False),
    sa.Column('charges', sa.JSON(), nullable=False),
    sa.Column('liquidated', sa.Boolean(), nullable=False),
    sa.Column('source_document_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_import_entry_lines_client_id_clients')),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], name=op.f('fk_import_entry_lines_source_document_id_documents')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_import_entry_lines_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_entry_lines')),
    sa.UniqueConstraint('client_id', 'entry_number', 'line_no', name=op.f('uq_import_entry_lines_client_id'))
    )
    with op.batch_alter_table('import_entry_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_entry_lines_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_entry_lines_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('designations',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('claim_id', sa.String(length=32), nullable=False),
    sa.Column('import_entry_line_id', sa.String(length=32), nullable=False),
    sa.Column('export_line_id', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('provision', sa.String(length=8), nullable=False),
    sa.Column('per_unit_recovery', server.db.types.Money(), nullable=False),
    sa.Column('recovery', server.db.types.Money(), nullable=False),
    sa.Column('recovery_low', server.db.types.Money(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('in_headline', sa.Boolean(), nullable=False),
    sa.Column('trace', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_designations_claim_id_claims')),
    sa.ForeignKeyConstraint(['export_line_id'], ['export_lines.id'], name=op.f('fk_designations_export_line_id_export_lines')),
    sa.ForeignKeyConstraint(['import_entry_line_id'], ['import_entry_lines.id'], name=op.f('fk_designations_import_entry_line_id_import_entry_lines')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_designations_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_designations'))
    )
    with op.batch_alter_table('designations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_designations_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_designations_export_line_id'), ['export_line_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_designations_import_entry_line_id'), ['import_entry_line_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_designations_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('designations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_designations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_designations_import_entry_line_id'))
        batch_op.drop_index(batch_op.f('ix_designations_export_line_id'))
        batch_op.drop_index(batch_op.f('ix_designations_claim_id'))

    op.drop_table('designations')
    with op.batch_alter_table('import_entry_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_entry_lines_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_import_entry_lines_client_id'))

    op.drop_table('import_entry_lines')
    with op.batch_alter_table('export_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_export_lines_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_export_lines_client_id'))

    op.drop_table('export_lines')
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_items_claim_id'))

    op.drop_table('checklist_items')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_claim_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_documents_status'))
        batch_op.drop_index(batch_op.f('ix_documents_client_id'))

    op.drop_table('documents')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_status'))
        batch_op.drop_index(batch_op.f('ix_claims_program_id'))

    op.drop_table('claims')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_tenant_id'))

    op.drop_table('audit_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))

    op.drop_table('users')
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_programs_client_id'))

    op.drop_table('programs')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_tenant_id'))

    op.drop_table('clients')
    op.drop_table('tenants')
    # ### end Alembic commands ###
